### ISSUE TITLE
Support for MPItrampoline 

### ISSUE THREAD

**Issue by idevcde** [JuliaParallel/MPIClusterManagers.jl#27]
Hi, I took part in todays session titled "EasyBuild Tech Talk: MPItrampoline" by @eschnett. This new technology seems to be very interesting and probably easy to use for not in depth technical MPI users thus I would like to ask if MPItrampoline is currently supported by MPIClusterManagers.jl or maybe is such a support planned in the future?

**Comment by simonbyrne** [comment]
Support for MPItrampoline is part of [MPI.jl](https://github.com/JuliaParallel/MPI.jl), which is used as part of MPIClusterManagers.jl. However we have not yet tagged a new release of that package (I hope to have one in the new year), so you will have to use the master version of that package to make use of it.

**Comment by idevcde** [comment]
Thank you for the information. Is there maybe any instruction about using MPItrampoline with MPI.jl, something ideally with recommended steps to follow?

**Comment by simonbyrne** [comment]
At the moment, the following should work:
```
using Pkg
ENV["JULIA_MPI_BINARY"] = MPItrampoline_jll"
Pkg.build("MPI")
```
but this may change before the release (we will update the docs once this is complete)

**Comment by eschnett** [comment]
To use MPI.jl with MPItrampoline, you need to:
- use the development version of MPI.jl: `Pkg.develop("MPI")`
- switch MPI.jl to MPItrampoline: Put the line `binary = "MPItrampoline_jll"` into `.julia/prefs/MPI.toml`
- rebuild MPI.jl: `Pkg.build("MPI")`

This will make MPI.jl use MPItrampoline. By default – if you don't set the `MPITRAMPOLINE_LIB` environment variable – MPItrampoline will use a built-in MPICH.

**Comment by eschnett** [comment]
It is important to note that any Yggdrasil packages that use MPI (e.g. `PETSC_jll`) would not be using `MPItrampoline_jll`. They would be using `MPICH_jll`, and this will lead to segfaults. The steps above work only for using `MPI.jl` directly with MPItrampoline, not (yet!) for using any external packages that use MPI.

**Comment by idevcde** [comment]
Thanks for the info simonbyrne and eschnett. I will try it as soon as possible.

**Comment by idevcde** [comment]
I have `Julia 1.8.0-DEV.1177` (alternatively I 've also `1.7`, however, I'd prefer to test `1.8`), `MPI v0.19.0 `~/.julia/dev/MPI`` and `MPIClusterManagers v0.2.1` ready. My `.julia/prefs/MPI.toml` says `binary = "MPItrampoline_jll"`. I understand that now I have to prepare the system and wrap `MPI` installation that is present on the system with `MPIwrapper`. I have working `Intel MPI` installation and `cmake version 3.10.2`. Do I have just to simply run those lines:

```
cmake -S . -B build -DMPIEXEC_EXECUTABLE=mpiexec -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$HOME/mpiwrapper
cmake --build build
cmake --install build
```

or do I have to make any downloads or adjustments? 

I'd appreciate any advice as a lot of things related to MPI is new for me.

**Comment by idevcde** [comment]
@eschnett, @simonbyrne I did as below. Next, I would like to use `MPIClusterManagers.jl` to add processes on two machines and run `Julia` code. How should I set `MPITRAMPOLINE_LIB` and `MPITRAMPOLINE_MPIEXEC` in such a case? Any advice pls?

```
~$ git clone https://github.com/eschnett/MPIwrapper.git
Cloning into 'MPIwrapper'...
remote: Enumerating objects: 693, done.
remote: Counting objects: 100% (693/693), done.
remote: Compressing objects: 100% (411/411), done.
remote: Total 693 (delta 397), reused 482 (delta 189), pack-reused 0
Receiving objects: 100% (693/693), 140.10 KiB | 982.00 KiB/s, done.
Resolving deltas: 100% (397/397), done.

```
`~$ cd MPIwrapper/`

```
~/MPIwrapper$ cmake -S . -B build -DMPIEXEC_EXECUTABLE=mpiexec -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=$HOME/mpiwrapper
-- The CXX compiler identification is GNU 9.3.0
-- The Fortran compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found MPI_CXX: /glob/development-tools/versions/oneapi/2022.1.1/oneapi/mpi/2021.5.0/lib/libmpicxx.so (found version "3.1")
-- Found MPI_Fortran: /glob/development-tools/versions/oneapi/2022.1.1/oneapi/mpi/2021.5.0/lib/libmpifort.so (found version "3.1")

```
```
-- Found MPI: TRUE (found version "3.1")
-- Using MPIEXEC_EXECUTABLE: /home/user/MPIwrapper/mpiexec
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/MPIwrapper/build

```
~/MPIwrapper$ cmake --build build
[ 16%] Generating mpiwrapper_definitions_fortran.h
[ 33%] Generating mpiabi_declarations.h
[ 50%] Generating mpiwrapper_definitions.h
Scanning dependencies of target mpiwrapper
[ 66%] Building CXX object CMakeFiles/mpiwrapper.dir/mpiwrapper.cxx.o
[ 83%] Building Fortran object CMakeFiles/mpiwrapper.dir/mpiwrapper.f.o
[100%] Linking CXX shared module libmpiwrapper.so
[100%] Built target mpiwrapper

```
~/MPIwrapper$ cmake --install build
-- Install configuration: "RelWithDebInfo"
-- Installing: /home/user/mpiwrapper/lib/libmpiwrapper.so
-- Installing: /home/user/mpiwrapper/bin/mpiwrapperexec
```

**Comment by eschnett** [comment]
@idevcde I assume that, for some reason, you don't want to use MPItrampoline with its built-in MPICH, but you want to instead use your own MPI. Still, to test things, I would first start with using the built-in MPICH.

If that is working fine, then you can install MPIwrapper. Yes, your instructions sound about right.

The environment variables `MPITRAMPOLINE_LIB` and `MPITRAMPOLINE_MPIEXEC` should be set before running the Julia executable. This should work:
```sh
export MPITRAMPOLINE_LIB=/home/user/mpiwrapper/lib/libmpiwrapper.so
export MPITRAMPOLINE_MPIEXEC= /home/user/mpiwrapper/bin/mpiwrapperexec
julia
```

You can, of course, set these variables from within Julia as well, if you do so before `MPItrampoline_jll` is loaded, i.e. before `MPI.jl` is loaded.

**Comment by idevcde** [comment]
>I assume that, for some reason, you don't want to use MPItrampoline with its built-in MPICH, but you want to instead use your own MPI. Still, to test things, I would first start with using the built-in MPICH.

Thank you for the information. Yes, this is correct. The main reason that stands behind the fact that I would like not to use built-in MPICH but MPI present on the system is that I was usually encountering problems when running Julia on more than one machine both with native Julia distributed capabilities as well as with MPI.jl. At the same time, I was not encountering problems when running Julia code with natively present mpirun command on more than one machine. Thus I was hoping to use MPItrampoline with system MPI installation from within Julia.

I fully agree re the built-in MPICH. Just tried to make it as short as possible. Of course, I did some testing. It seems that on one machine MPIClusterManagers with MPItrampoline and with its built-in MPICH works fine. Below please find my test. As for the test of MPItrampoline on more than one machine pls allow me some time. I am currently running additional tests. Moreover, today I received some new info regarding native Julia distributed capabilities. I just need some time to run those tests in an ordered manner.


```
# Test of MPItrampoline with built-in MPICH

# Julia 1.8.0-DEV.1177, MPI v0.19.0 ~/.julia/dev/MPI and MPIClusterManagers v0.2.1, .julia/prefs/MPI.toml says binary = "MPItrampoline_jll"

./julia

# I am setting env variables inside julia
julia> ENV["MPITRAMPOLINE_LIB"] = "/home/user/mpiwrapper/lib/libmpiwrapper.so"
"/home/user/mpiwrapper/lib/libmpiwrapper.so"

julia> ENV["MPITRAMPOLINE_MPIEXEC"] = "/home/user/mpiwrapper/bin/mpiwrapperexec"
"/home/user/mpiwrapper/bin/mpiwrapperexec"

# to import MPIManager
julia> using MPIClusterManagers

# need to also import Distributed to use addprocs()
julia> using Distributed

# specify, number of mpi workers, launch cmd, etc.
julia> manager=MPIManager(np=12)
MPI.MPIManager(np=12,launched=false,mode=MPI_ON_WORKERS)

julia> addprocs(manager)
12-element Vector{Int64}:
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
```

And now I understand that I can do distributed calculations with added workers

a) with Julia code by

```
julia> @everywhere begin
	       Julia code
	end
```

or 

b) with MPI code by

```
julia> @mpi_do manager begin
		MPI code
	  end
```

I hope that my understanding re option a) is correct as I see on my screen calculations with the use of Julia code taking place. If not and if MPIClusterManagers / MPItrampoline are only for the use of MPI code as in point b) could you pls correct me. (I have only rather basic understanding about those things).

**Comment by idevcde** [comment]
@eschnett, @simonbyrne, I am really sorry for such a long delay in reply. Immediately I was able to do the basic tests, however, due to some circumstances, I still have to carry out the more detailed ones. I would like to underline my interest in this topic. I hope to carry additional tests as soon as the circumstances allow. Thank you once again for the MPItrampoline package and for all the information.
